# Generated by Django 5.2.8 on 2026-08-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=200)),
                ('job_positions', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('official_url', models.URLField()),
            ],
        ),
    ]
