# Generated by Django 5.2.8 on 2026-08-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='status',
        ),
    ]
